### ISSUE TITLE
Scraping URLs! 

### ISSUE THREAD

**Issue by meilinli123** [meilinli123/eco395m-FinalProject#10]
Nancy: "Jaguar", "Jeep", "Jensen", "Kaiser", "Karma", "Kia", "Koenigsegg", "Lamborghini", "Land Rover", "LaSalle",/// "Panoz", "Plymouth", "Polestar", "Pontiac", "Porsche", "RAM", "Renault", "Rivian", "Rolls-Royce", "Rover", "Saab", "Saturn", "Scion", "smart", "Spyker"

Tianyu: "Bentley", "BMW", "Bugatti", "Buick", "Cadillac", "Chevrolet", "Chrysler", "Daewoo", "Datsun", "Delorean",
"Geo", "GMC", "Honda", "Hudson", "Hummer", "Hyundai", "INEOS", "INFINITI", "International", "Isuzu", "Lexus", "Lincoln", "Lotus", "Lucid", "Maserati", "Maybach", "Mazda", "McLaren", "Mercedes-Benz", "Mercury", "MG", "MINI", "Mitsubishi", "Morgan", "Nash", "Nissan", "Oldsmobile", "Opel", "Packard", "Pagani", 

Machete: "Desoto", "DeTomaso", "Dodge", "Eagle", "Edsel", "Ferrari", "FIAT", "Fisker", "Ford", "Genesis",

Freda: "Studebaker", "Subaru", "Sunbeam", "Suzuki", "Tesla", "Toyota", "Triumph", "Volkswagen", "Volvo", "Willys"

**Comment by PlaneswalkerTeferi** [comment]
till "Pagani" all finished

**Comment by NancyQin0503** [comment]
Finished: "Panoz", "Plymouth", "Polestar", "Pontiac", "Porsche", "RAM", "Renault", "Rivian", "Rolls-Royce", "Rover", "Saab", "Saturn", "Scion", "smart", "Spyker"

**Comment by 221B-Baker-St** [comment]
Finished  "Desoto", "DeTomaso", "Dodge", "Eagle", "Edsel", "Ferrari", "FIAT", "Fisker", "Ford", "Genesis",
